<template>
  <div class="table-box">
    <div
      class="table"
      style="margin-top: 10px"
    >
      <RowTable
        :color="color"
        :title="directName"
        :mesInfo="leftData"
        :titleHead="titleHead"
        :directName="directName"
        :rowSpanNumber="rowSpanNumber1"
        @handleClick="namesClick"
        :setTrueOrFalse="setTrueOrFalse"
        :cooprMode="cooprMode"
        :headerObj="leftObj"
      />
      <RowTable
        :color="color2"
        :title="directName2"
        :mesInfo="rightData"
        :titleHead="titleHead"
        :directName="directName2"
        :rowSpanNumber="rowSpanNumber2"
        @handleClick="managerClick"
        :setTrueOrFalse="setTrueOrFalse"
        :cooprMode="cooprMode"
        :headerObj="rightObj"
      />
    </div>
    <!-- <div
      class="table"
      style="margin-top: 10px"
    >
      <SellSportTable
        :mesInfo="tableList.innerDirect"
        :title="directName"
        :color="color"
        @handleClick="namesClick"
      />
      <SellSportTable
        :mesInfo="tableList.outerDirect"
        :title="directName2"
        :color="color2"
        @handleClick="managerClick"
      />
    </div> -->
  </div>
</template>
<script>
// import SaleSummaryTable from "./SaleSummaryTable.vue";
// import SellSportTable from "./SellSportTable.vue";
import RowTable from "./ProRowTable.vue";
export default {
  components: {
    // SellSportTable
    // SaleSummaryTable,
    RowTable,
  },
  props:{
    leftData:{
      type:Array,
      default:function(){ return []}
    },
    titleHead:{
      type:Object,
      default:function(){ return {}}
    },
    rightData:{
      type:Array,
      default:function(){ return []}
    },
    rowSpanNumber1:{
      type:Array,
      default:function(){ return []},
    },
    rowSpanNumber2:{
      type:Array,
      default:function(){ return []},
    },
    leftObj:{
      type:Object,
    },
    rightObj:{
      type:Object,
    }
  },
  data() {
    return {
      color: "linear-gradient(to right , #50C0FF,#5AFFA3,#66FFFF) ",
      color2: "linear-gradient(to right , #1B6FFF, #7A5AFF, #7066FF) ",
      // directName: computed(() => Store.state.tableOneHeading),
      // directName2: computed(() => Store.state.tableTwoHeading),
      cooprMode: "渠道",
      directName: "内销",
      directName2: "外销",
      setTrueOrFalse: true,
      innerTableList:[
          {
            directName: "内销",
            marketChannel: "线上",
            marketCenter: null,
            manager: "张茉欧",
            cooprMode: "京东",
            businessEntityName1: 23,
            businessEntityName2: 23,
            businessEntityName3: 23,
            businessEntityName4: 23,
            businessEntityName5: 23,
            businessEntityName6: 23,
            saleVolume1: 34,
            saleVolume2: 34,
            saleVolume3: 34,
            saleVolume4: 34,
            saleVolume5: 34,
            saleVolume6: 34,
            completeRadioAll: null,
            cnyAmt: 22,
            saleTaskAmt: 60,
            saleVolumeAll: 50,
            dateRadio: 1,
          },
          {
            directName: "内销",
            marketChannel: "线上",
            marketCenter: null,
            manager: "张茉欧",
            cooprMode: "淘系",
            businessEntityName1: 23,
            businessEntityName2: 23,
            businessEntityName3: 23,
            businessEntityName4: 23,
            businessEntityName5: 23,
            businessEntityName6: 23,
            saleVolume1: 34,
            saleVolume2: 34,
            saleVolume3: 34,
            saleVolume4: 34,
            saleVolume5: 34,
            saleVolume6: 34,
            completeRadioAll: null,
            cnyAmt: 23,
            saleTaskAmt: 60,
            saleVolumeAll: 50,
            dateRadio: 1,
          },
          {
            directName: "内销",
            marketChannel: "线上",
            marketCenter: null,
            manager: "张茉欧",
            cooprMode: "拼多多",
            businessEntityName1: 23,
            businessEntityName2: 23,
            businessEntityName3: 23,
            businessEntityName4: 23,
            businessEntityName5: 23,
            businessEntityName6: 23,
            saleVolume1: 34,
            saleVolume2: 34,
            saleVolume3: 34,
            saleVolume4: 34,
            saleVolume5: 34,
            saleVolume6: 34,
            completeRadioAll: null,
            cnyAmt: 24,
            saleTaskAmt: 60,
            saleVolumeAll: 50,
            dateRadio: 1,
          },
          {
            directName: "内销",
            marketChannel: "线下",
            marketCenter: null,
            manager: "张茉欧",
            cooprMode: "分中心",
            businessEntityName1: 23,
            businessEntityName2: 23,
            businessEntityName3: 23,
            businessEntityName4: 23,
            businessEntityName5: 23,
            businessEntityName6: 23,
            saleVolume1: 34,
            saleVolume2: 34,
            saleVolume3: 34,
            saleVolume4: 34,
            saleVolume5: 34,
            saleVolume6: 34,
            completeRadioAll: null,
            cnyAmt: 24,
            saleTaskAmt: 60,
            saleVolumeAll: 50,
            dateRadio: 1,
          },
          {
            directName: "内销",
            marketChannel: "线下",
            marketCenter: null,
            manager: "张茉欧",
            cooprMode: "下沉",
            businessEntityName1: 23,
            businessEntityName2: 23,
            businessEntityName3: 23,
            businessEntityName4: 23,
            businessEntityName5: 23,
            businessEntityName6: 23,
            saleVolume1: 34,
            saleVolume2: 34,
            saleVolume3: 34,
            saleVolume4: 34,
            saleVolume5: 34,
            saleVolume6: 34,
            completeRadioAll: null,
            cnyAmt: 24,
            saleTaskAmt: 60,
            saleVolumeAll: 50,
            dateRadio: 1,
          },
          {
            directName: "内销",
            marketChannel: "线下",
            marketCenter: null,
            manager: "张茉欧",
            cooprMode: "新渠道",
            businessEntityName1: 23,
            businessEntityName2: 23,
            businessEntityName3: 23,
            businessEntityName4: 23,
            businessEntityName5: 23,
            businessEntityName6: 23,
            saleVolume1: 34,
            saleVolume2: 34,
            saleVolume3: 34,
            saleVolume4: 34,
            saleVolume5: 34,
            saleVolume6: 34,
            completeRadioAll: null,
            cnyAmt: 24,
            saleTaskAmt: 60,
            saleVolumeAll: 50,
            dateRadio: 1,
          },
          {
            directName: "外销",
            marketChannel: "合计",
            cooprMode: "",
            marketCenter: null,
            manager: null,
            businessEntityName1: 23,
            businessEntityName2: 23,
            businessEntityName3: 23,
            businessEntityName4: 23,
            businessEntityName5: 23,
            businessEntityName6: 23,
            saleVolume1: 34,
            saleVolume2: 34,
            saleVolume3: 34,
            saleVolume4: 34,
            saleVolume5: 34,
            saleVolume6: 34,
            completeRadioAll: null,
            cnyAmt: 24,
            saleTaskAmt: 60,
            saleVolumeAll: 50,
            dateRadio: 1,
          },
        ],
      outerTableList: [
          {
            directName: "外销",
            marketChannel: "大区",
            marketCenter: null,
            manager: null,
            cooprMode: "北美",
            businessEntityName1: 23,
            businessEntityName2: 23,
            businessEntityName3: 23,
            businessEntityName4: 23,
            businessEntityName5: 23,
            businessEntityName6: 23,
            saleVolume1: 34,
            saleVolume2: 34,
            saleVolume3: 34,
            saleVolume4: 34,
            saleVolume5: 34,
            saleVolume6: 34,
            completeRadioAll: null,
            cnyAmt: 24,
            saleTaskAmt: 60,
            saleVolumeAll: 50,
            dateRadio: 1,
          },
          {
            directName: "外销",
            marketChannel: "大区",
            cooprMode: "亚太",
            marketCenter: null,
            manager: null,
            businessEntityName1: 23,
            businessEntityName2: 23,
            businessEntityName3: 23,
            businessEntityName4: 23,
            businessEntityName5: 23,
            businessEntityName6: 23,
            saleVolume1: 34,
            saleVolume2: 34,
            saleVolume3: 34,
            saleVolume4: 34,
            saleVolume5: 34,
            saleVolume6: 34,
            completeRadioAll: null,
            cnyAmt: 24,
            saleTaskAmt: 60,
            saleVolumeAll: 50,
            dateRadio: 1,
          },
          {
            directName: "外销",
            marketChannel: "大区",
            cooprMode: "中东非",
            marketCenter: null,
            manager: null,
            businessEntityName1: 23,
            businessEntityName2: 23,
            businessEntityName3: 23,
            businessEntityName4: 23,
            businessEntityName5: 23,
            businessEntityName6: 23,
            saleVolume1: 34,
            saleVolume2: 34,
            saleVolume3: 34,
            saleVolume4: 34,
            saleVolume5: 34,
            saleVolume6: 34,
            completeRadioAll: null,
            cnyAmt: 24,
            saleTaskAmt: 60,
            saleVolumeAll: 50,
            dateRadio: 1,
          },
          {
            directName: "外销",
            marketChannel: "大区",
            cooprMode: "日本",
            marketCenter: null,
            manager: null,
            businessEntityName1: 23,
            businessEntityName2: 23,
            businessEntityName3: 23,
            businessEntityName4: 23,
            businessEntityName5: 23,
            businessEntityName6: 23,
            saleVolume1: 34,
            saleVolume2: 34,
            saleVolume3: 34,
            saleVolume4: 34,
            saleVolume5: 34,
            saleVolume6: 34,
            completeRadioAll: null,
            cnyAmt: 24,
            saleTaskAmt: 60,
            saleVolumeAll: 50,
            dateRadio: 1,
          },
          {
            directName: "外销",
            marketChannel: "大区",
            cooprMode: "韩国",
            marketCenter: null,
            manager: null,
            businessEntityName1: 23,
            businessEntityName2: 23,
            businessEntityName3: 23,
            businessEntityName4: 23,
            businessEntityName5: 23,
            businessEntityName6: 23,
            saleVolume1: 34,
            saleVolume2: 34,
            saleVolume3: 34,
            saleVolume4: 34,
            saleVolume5: 34,
            saleVolume6: 34,
            completeRadioAll: null,
            cnyAmt: 24,
            saleTaskAmt: 60,
            saleVolumeAll: 50,
            dateRadio: 1,
          },
          {
            directName: "外销",
            marketChannel: "大区",
            cooprMode: "拉美",
            marketCenter: null,
            manager: null,
            businessEntityName1: 23,
            businessEntityName2: 23,
            businessEntityName3: 23,
            businessEntityName4: 23,
            businessEntityName5: 23,
            businessEntityName6: 23,
            saleVolume1: 34,
            saleVolume2: 34,
            saleVolume3: 34,
            saleVolume4: 34,
            saleVolume5: 34,
            saleVolume6: 34,
            completeRadioAll: null,
            cnyAmt: 24,
            saleTaskAmt: 60,
            saleVolumeAll: 50,
            dateRadio: 1,
          },
          {
            directName: "外销",
            marketChannel: "合计",
            cooprMode: "拉美",
            marketCenter: null,
            manager: null,
            businessEntityName1: 23,
            businessEntityName2: 23,
            businessEntityName3: 23,
            businessEntityName4: 23,
            businessEntityName5: 23,
            businessEntityName6: 23,
            saleVolume1: 34,
            saleVolume2: 34,
            saleVolume3: 34,
            saleVolume4: 34,
            saleVolume5: 34,
            saleVolume6: 34,
            completeRadioAll: null,
            cnyAmt: 24,
            saleTaskAmt: 60,
            saleVolumeAll: 50,
            dateRadio: 1,
          },
        ],


      tableList: {
        innerDirect: [
          {
            directName: "内销",
            marketChannel: "线上",
            marketCenter: null,
            manager: "张茉欧",
            cooprMode: "京东",
            businessEntityName1: 23,
            businessEntityName2: 23,
            businessEntityName3: 23,
            businessEntityName4: 23,
            businessEntityName5: 23,
            businessEntityName6: 23,
            saleVolume1: 34,
            saleVolume2: 34,
            saleVolume3: 34,
            saleVolume4: 34,
            saleVolume5: 34,
            saleVolume6: 34,
            completeRadioAll: null,
            cnyAmt: 22,
            saleTaskAmt: 60,
            saleVolumeAll: 50,
            dateRadio: 1,
          },
          {
            directName: "内销",
            marketChannel: "线上",
            marketCenter: null,
            manager: "张茉欧",
            cooprMode: "淘系",
            businessEntityName1: 23,
            businessEntityName2: 23,
            businessEntityName3: 23,
            businessEntityName4: 23,
            businessEntityName5: 23,
            businessEntityName6: 23,
            saleVolume1: 34,
            saleVolume2: 34,
            saleVolume3: 34,
            saleVolume4: 34,
            saleVolume5: 34,
            saleVolume6: 34,
            completeRadioAll: null,
            cnyAmt: 23,
            saleTaskAmt: 60,
            saleVolumeAll: 50,
            dateRadio: 1,
          },
          {
            directName: "内销",
            marketChannel: "线上",
            marketCenter: null,
            manager: "张茉欧",
            cooprMode: "拼多多",
            businessEntityName1: 23,
            businessEntityName2: 23,
            businessEntityName3: 23,
            businessEntityName4: 23,
            businessEntityName5: 23,
            businessEntityName6: 23,
            saleVolume1: 34,
            saleVolume2: 34,
            saleVolume3: 34,
            saleVolume4: 34,
            saleVolume5: 34,
            saleVolume6: 34,
            completeRadioAll: null,
            cnyAmt: 24,
            saleTaskAmt: 60,
            saleVolumeAll: 50,
            dateRadio: 1,
          },
          {
            directName: "内销",
            marketChannel: "线下",
            marketCenter: null,
            manager: "张茉欧",
            cooprMode: "分中心",
            businessEntityName1: 23,
            businessEntityName2: 23,
            businessEntityName3: 23,
            businessEntityName4: 23,
            businessEntityName5: 23,
            businessEntityName6: 23,
            saleVolume1: 34,
            saleVolume2: 34,
            saleVolume3: 34,
            saleVolume4: 34,
            saleVolume5: 34,
            saleVolume6: 34,
            completeRadioAll: null,
            cnyAmt: 24,
            saleTaskAmt: 60,
            saleVolumeAll: 50,
            dateRadio: 1,
          },
          {
            directName: "内销",
            marketChannel: "线下",
            marketCenter: null,
            manager: "张茉欧",
            cooprMode: "下沉",
            businessEntityName1: 23,
            businessEntityName2: 23,
            businessEntityName3: 23,
            businessEntityName4: 23,
            businessEntityName5: 23,
            businessEntityName6: 23,
            saleVolume1: 34,
            saleVolume2: 34,
            saleVolume3: 34,
            saleVolume4: 34,
            saleVolume5: 34,
            saleVolume6: 34,
            completeRadioAll: null,
            cnyAmt: 24,
            saleTaskAmt: 60,
            saleVolumeAll: 50,
            dateRadio: 1,
          },
          {
            directName: "内销",
            marketChannel: "线下",
            marketCenter: null,
            manager: "张茉欧",
            cooprMode: "新渠道",
            businessEntityName1: 23,
            businessEntityName2: 23,
            businessEntityName3: 23,
            businessEntityName4: 23,
            businessEntityName5: 23,
            businessEntityName6: 23,
            saleVolume1: 34,
            saleVolume2: 34,
            saleVolume3: 34,
            saleVolume4: 34,
            saleVolume5: 34,
            saleVolume6: 34,
            completeRadioAll: null,
            cnyAmt: 24,
            saleTaskAmt: 60,
            saleVolumeAll: 50,
            dateRadio: 1,
          },
          {
            directName: "外销",
            marketChannel: "合计",
            cooprMode: "",
            marketCenter: null,
            manager: null,
            businessEntityName1: 23,
            businessEntityName2: 23,
            businessEntityName3: 23,
            businessEntityName4: 23,
            businessEntityName5: 23,
            businessEntityName6: 23,
            saleVolume1: 34,
            saleVolume2: 34,
            saleVolume3: 34,
            saleVolume4: 34,
            saleVolume5: 34,
            saleVolume6: 34,
            completeRadioAll: null,
            cnyAmt: 24,
            saleTaskAmt: 60,
            saleVolumeAll: 50,
            dateRadio: 1,
          },
        ],
        outerDirect: [
          {
            directName: "外销",
            marketChannel: "大区",
            marketCenter: null,
            manager: null,
            cooprMode: "北美",
            businessEntityName1: 23,
            businessEntityName2: 23,
            businessEntityName3: 23,
            businessEntityName4: 23,
            businessEntityName5: 23,
            businessEntityName6: 23,
            saleVolume1: 34,
            saleVolume2: 34,
            saleVolume3: 34,
            saleVolume4: 34,
            saleVolume5: 34,
            saleVolume6: 34,
            completeRadioAll: null,
            cnyAmt: 24,
            saleTaskAmt: 60,
            saleVolumeAll: 50,
            dateRadio: 1,
          },
          {
            directName: "外销",
            marketChannel: "大区",
            cooprMode: "亚太",
            marketCenter: null,
            manager: null,
            businessEntityName1: 23,
            businessEntityName2: 23,
            businessEntityName3: 23,
            businessEntityName4: 23,
            businessEntityName5: 23,
            businessEntityName6: 23,
            saleVolume1: 34,
            saleVolume2: 34,
            saleVolume3: 34,
            saleVolume4: 34,
            saleVolume5: 34,
            saleVolume6: 34,
            completeRadioAll: null,
            cnyAmt: 24,
            saleTaskAmt: 60,
            saleVolumeAll: 50,
            dateRadio: 1,
          },
          {
            directName: "外销",
            marketChannel: "大区",
            cooprMode: "中东非",
            marketCenter: null,
            manager: null,
            businessEntityName1: 23,
            businessEntityName2: 23,
            businessEntityName3: 23,
            businessEntityName4: 23,
            businessEntityName5: 23,
            businessEntityName6: 23,
            saleVolume1: 34,
            saleVolume2: 34,
            saleVolume3: 34,
            saleVolume4: 34,
            saleVolume5: 34,
            saleVolume6: 34,
            completeRadioAll: null,
            cnyAmt: 24,
            saleTaskAmt: 60,
            saleVolumeAll: 50,
            dateRadio: 1,
          },
          {
            directName: "外销",
            marketChannel: "大区",
            cooprMode: "日本",
            marketCenter: null,
            manager: null,
            businessEntityName1: 23,
            businessEntityName2: 23,
            businessEntityName3: 23,
            businessEntityName4: 23,
            businessEntityName5: 23,
            businessEntityName6: 23,
            saleVolume1: 34,
            saleVolume2: 34,
            saleVolume3: 34,
            saleVolume4: 34,
            saleVolume5: 34,
            saleVolume6: 34,
            completeRadioAll: null,
            cnyAmt: 24,
            saleTaskAmt: 60,
            saleVolumeAll: 50,
            dateRadio: 1,
          },
          {
            directName: "外销",
            marketChannel: "大区",
            cooprMode: "韩国",
            marketCenter: null,
            manager: null,
            businessEntityName1: 23,
            businessEntityName2: 23,
            businessEntityName3: 23,
            businessEntityName4: 23,
            businessEntityName5: 23,
            businessEntityName6: 23,
            saleVolume1: 34,
            saleVolume2: 34,
            saleVolume3: 34,
            saleVolume4: 34,
            saleVolume5: 34,
            saleVolume6: 34,
            completeRadioAll: null,
            cnyAmt: 24,
            saleTaskAmt: 60,
            saleVolumeAll: 50,
            dateRadio: 1,
          },
          {
            directName: "外销",
            marketChannel: "大区",
            cooprMode: "拉美",
            marketCenter: null,
            manager: null,
            businessEntityName1: 23,
            businessEntityName2: 23,
            businessEntityName3: 23,
            businessEntityName4: 23,
            businessEntityName5: 23,
            businessEntityName6: 23,
            saleVolume1: 34,
            saleVolume2: 34,
            saleVolume3: 34,
            saleVolume4: 34,
            saleVolume5: 34,
            saleVolume6: 34,
            completeRadioAll: null,
            cnyAmt: 24,
            saleTaskAmt: 60,
            saleVolumeAll: 50,
            dateRadio: 1,
          },
          {
            directName: "外销",
            marketChannel: "合计",
            cooprMode: "拉美",
            marketCenter: null,
            manager: null,
            businessEntityName1: 23,
            businessEntityName2: 23,
            businessEntityName3: 23,
            businessEntityName4: 23,
            businessEntityName5: 23,
            businessEntityName6: 23,
            saleVolume1: 34,
            saleVolume2: 34,
            saleVolume3: 34,
            saleVolume4: 34,
            saleVolume5: 34,
            saleVolume6: 34,
            completeRadioAll: null,
            cnyAmt: 24,
            saleTaskAmt: 60,
            saleVolumeAll: 50,
            dateRadio: 1,
          },
        ],
        title: {
          businessEntityName1: "环境",
          businessEntityName2: "烹饪",
          businessEntityName3: "电磁",
          businessEntityName4: "调理",
          businessEntityName5: "电动",
          businessEntityName6: "饮品",
        },
      },
      demosticDirectOnOnline: {
        title: {
          manager: "责任人",
          saleTaskAmt: "责任制",
          businessEntityName1: "累计达成",
          businessEntityName2: "任务完成率",
          businessEntityName3: "毛利率",
          businessEntityName4: "周转天数",
          businessEntityName5: "说到做到",
          businessEntityName6: "排名",
        },
        innerDirect: [
          {
            directName: "线上",
            marketChannel: "京东",
            marketCenter: null,
            cooprLevel2Mmanager: "张茉欧",
            saleTaskAmt: "22",
            cnyAmt: 22,
            cnyAmtRadio: 22,
            ProfitRadio: 22,
            turnoverDays: 22,
            turnoverDays: 22,
            amtFinish: 1,
            ranking: 1,
            cnyAmt: 22,
            dateRadio: 1,
          },
          {
            directName: "线上",
            marketChannel: "淘系",
            marketCenter: null,
            cooprLevel2Mmanager: "张茉欧",
            saleTaskAmt: "22",
            cnyAmt: 22,
            cnyAmtRadio: 22,
            cnyAmtRadio: 22,
            turnoverDays: 22,
            turnoverDays: 22,
            ProfitRadio: 22,
            amtFinish: 1,
            ranking: 1,
            cnyAmt: 199,
            dateRadio: 1,
          },
          {
            directName: "线上",
            marketChannel: "拼多多",
            marketCenter: null,
            cooprLevel2Mmanager: "张茉欧",
            saleTaskAmt: "22",
            cnyAmt: 22,
            cnyAmtRadio: 22,
            cnyAmtRadio: 22,
            turnoverDays: 22,
            ProfitRadio: 22,
            turnoverDays: 22,
            amtFinish: 1,
            ranking: 1,
            cnyAmt: 199,
            dateRadio: 1,
          },
          {
            directName: "线上",
            marketChannel: "美的平台",
            marketCenter: null,
            cooprLevel2Mmanager: "张茉欧",
            saleTaskAmt: "22",
            cnyAmt: 22,
            cnyAmtRadio: 22,
            cnyAmtRadio: 22,
            turnoverDays: 22,
            turnoverDays: 22,
            ProfitRadio: 22,
            amtFinish: 1,
            ranking: 1,
            cnyAmt: 199,
            dateRadio: 1,
          },
          {
            directName: "线上",
            marketChannel: "兴趣电商",
            marketCenter: null,
            cooprLevel2Mmanager: "张茉欧",
            saleTaskAmt: "22",
            cnyAmt: 22,
            cnyAmtRadio: 22,
            cnyAmtRadio: 22,
            ProfitRadio: 22,
            turnoverDays: 22,
            turnoverDays: 22,
            amtFinish: 1,
            ranking: 1,
            cnyAmt: 199,
            dateRadio: 1,
          },
          {
            directName: "线上",
            marketChannel: "天猫",
            marketCenter: null,
            cooprLevel2Mmanager: "张茉欧",
            saleTaskAmt: "22",
            cnyAmt: 22,
            ProfitRadio: 22,
            cnyAmtRadio: 22,
            cnyAmtRadio: 22,
            turnoverDays: 22,
            turnoverDays: 22,
            amtFinish: 1,
            ranking: 1,
            cnyAmt: 199,
            dateRadio: 1,
          },
          {
            directName: "线上",
            marketChannel: "合计",
            marketCenter: null,
            cooprLevel2Mmanager: "张茉欧",
            saleTaskAmt: "22",
            cnyAmt: 22,
            ProfitRadio: 22,
            cnyAmtRadio: 22,
            cnyAmtRadio: 22,
            turnoverDays: 22,
            turnoverDays: 22,
            amtFinish: 1,
            ranking: 1,
            cnyAmt: 199,
            dateRadio: 1,
          },
        ],
        outerDirect: [
          {
            directName: "线下",
            marketChannel: "型号1",
            marketCenter: null,
            cooprLevel2Mmanager: "张茉欧",
            saleTaskAmt: "22",
            cnyAmt: 22,
            ProfitRadio: 22,
            cnyAmtRadio: 22,
            cnyAmtRadio: 22,
            turnoverDays: 22,
            turnoverDays: 22,
            amtFinish: 1,
            ranking: 1,
            cnyAmt: 199,
            dateRadio: 1,
          },
          {
            directName: "线下",
            marketChannel: "型号2",
            marketCenter: null,
            cooprLevel2Mmanager: "张茉欧",
            saleTaskAmt: "22",
            cnyAmt: 22,
            cnyAmtRadio: 22,
            ProfitRadio: 22,
            cnyAmtRadio: 22,
            turnoverDays: 22,
            turnoverDays: 22,
            amtFinish: 1,
            ranking: 1,
            cnyAmt: 199,
            dateRadio: 1,
          },
          {
            directName: "线下",
            marketChannel: "型号3",
            marketCenter: null,
            cooprLevel2Mmanager: "张茉欧",
            saleTaskAmt: "22",
            ProfitRadio: 22,
            cnyAmt: 22,
            cnyAmtRadio: 22,
            cnyAmtRadio: 22,
            turnoverDays: 22,
            turnoverDays: 22,
            amtFinish: 1,
            ranking: 1,
            cnyAmt: 199,
            dateRadio: 1,
          },
          {
            directName: "线下",
            marketChannel: "型号4",
            marketCenter: null,
            cooprLevel2Mmanager: "张茉欧",
            saleTaskAmt: "22",
            cnyAmt: 22,
            cnyAmtRadio: 22,
            ProfitRadio: 22,
            cnyAmtRadio: 22,
            turnoverDays: 22,
            turnoverDays: 22,
            amtFinish: 1,
            ranking: 1,
            cnyAmt: 199,
            dateRadio: 1,
          },
          {
            directName: "线下",
            marketChannel: "型号5",
            marketCenter: null,
            cooprLevel2Mmanager: "张茉欧",
            saleTaskAmt: "22",
            ProfitRadio: 22,
            cnyAmt: 22,
            cnyAmtRadio: 22,
            cnyAmtRadio: 22,
            turnoverDays: 22,
            turnoverDays: 22,
            amtFinish: 1,
            ranking: 1,
            cnyAmt: 199,
            dateRadio: 1,
          },
          {
            directName: "线下",
            marketChannel: "型号6",
            marketCenter: null,
            cooprLevel2Mmanager: "张茉欧",
            saleTaskAmt: "22",
            ProfitRadio: 22,
            cnyAmt: 22,
            cnyAmtRadio: 22,
            cnyAmtRadio: 22,
            turnoverDays: 22,
            turnoverDays: 22,
            amtFinish: 1,
            ranking: 1,
            cnyAmt: 199,
            dateRadio: 1,
          },
          {
            directName: "线下",
            marketChannel: "合计",
            marketCenter: null,
            cooprLevel2Mmanager: "张茉欧",
            saleTaskAmt: "22",
            cnyAmt: 22,
            ProfitRadio: 22,
            cnyAmtRadio: 22,
            cnyAmtRadio: 22,
            turnoverDays: 22,
            turnoverDays: 22,
            amtFinish: 1,
            cnyAmt: 199,
            dateRadio: 1,
          },
        ],
      },
      demosticDirectOnOnlineGuest: {
        title: {
          manager: "责任人",
          saleTaskAmt: "责任制",
          businessEntityName1: "累计达成",
          businessEntityName2: "任务完成率",
          businessEntityName3: "毛利率",
          businessEntityName4: "周转天数",
          businessEntityName5: "说到做到",
          businessEntityName6: "排名",
        },
        innerDirect: [
          {
            directName: "线上",
            marketChannel: "京东",
            marketCenter: null,
            cooprLevel2Mmanager: "张茉欧",
            saleTaskAmt: "22",
            cnyAmt: 22,
            cnyAmtRadio: 22,
            ProfitRadio: 22,
            turnoverDays: 22,
            turnoverDays: 22,
            amtFinish: 1,
            ranking: 1,
            cnyAmt: 22,
            dateRadio: 1,
          },
          {
            directName: "线上",
            marketChannel: "淘系",
            marketCenter: null,
            cooprLevel2Mmanager: "张茉欧",
            saleTaskAmt: "22",
            cnyAmt: 22,
            cnyAmtRadio: 22,
            cnyAmtRadio: 22,
            turnoverDays: 22,
            turnoverDays: 22,
            ProfitRadio: 22,
            amtFinish: 1,
            ranking: 1,
            cnyAmt: 199,
            dateRadio: 1,
          },
          {
            directName: "线上",
            marketChannel: "拼多多",
            marketCenter: null,
            cooprLevel2Mmanager: "张茉欧",
            saleTaskAmt: "22",
            cnyAmt: 22,
            cnyAmtRadio: 22,
            cnyAmtRadio: 22,
            turnoverDays: 22,
            ProfitRadio: 22,
            turnoverDays: 22,
            amtFinish: 1,
            ranking: 1,
            cnyAmt: 199,
            dateRadio: 1,
          },
          {
            directName: "线上",
            marketChannel: "美的平台",
            marketCenter: null,
            cooprLevel2Mmanager: "张茉欧",
            saleTaskAmt: "22",
            cnyAmt: 22,
            cnyAmtRadio: 22,
            cnyAmtRadio: 22,
            turnoverDays: 22,
            turnoverDays: 22,
            ProfitRadio: 22,
            amtFinish: 1,
            ranking: 1,
            cnyAmt: 199,
            dateRadio: 1,
          },
          {
            directName: "线上",
            marketChannel: "兴趣电商",
            marketCenter: null,
            cooprLevel2Mmanager: "张茉欧",
            saleTaskAmt: "22",
            cnyAmt: 22,
            cnyAmtRadio: 22,
            cnyAmtRadio: 22,
            ProfitRadio: 22,
            turnoverDays: 22,
            turnoverDays: 22,
            amtFinish: 1,
            ranking: 1,
            cnyAmt: 199,
            dateRadio: 1,
          },
          {
            directName: "线上",
            marketChannel: "天猫",
            marketCenter: null,
            cooprLevel2Mmanager: "张茉欧",
            saleTaskAmt: "22",
            cnyAmt: 22,
            ProfitRadio: 22,
            cnyAmtRadio: 22,
            cnyAmtRadio: 22,
            turnoverDays: 22,
            turnoverDays: 22,
            amtFinish: 1,
            ranking: 1,
            cnyAmt: 199,
            dateRadio: 1,
          },
          {
            directName: "线上",
            marketChannel: "合计",
            marketCenter: null,
            cooprLevel2Mmanager: "张茉欧",
            saleTaskAmt: "22",
            cnyAmt: 22,
            ProfitRadio: 22,
            cnyAmtRadio: 22,
            cnyAmtRadio: 22,
            turnoverDays: 22,
            turnoverDays: 22,
            amtFinish: 1,
            ranking: 1,
            cnyAmt: 199,
            dateRadio: 1,
          },
        ],
        outerDirect: [
          {
            directName: "线上",
            marketChannel: "京东",
            marketCenter: null,
            cooprLevel2Mmanager: "张茉欧",
            saleTaskAmt: "22",
            cnyAmt: 22,
            cnyAmtRadio: 22,
            ProfitRadio: 22,
            turnoverDays: 22,
            turnoverDays: 22,
            amtFinish: 1,
            ranking: 1,
            cnyAmt: 22,
            dateRadio: 1,
          },
          {
            directName: "线上",
            marketChannel: "淘系",
            marketCenter: null,
            cooprLevel2Mmanager: "张茉欧",
            saleTaskAmt: "22",
            cnyAmt: 22,
            cnyAmtRadio: 22,
            cnyAmtRadio: 22,
            turnoverDays: 22,
            turnoverDays: 22,
            ProfitRadio: 22,
            amtFinish: 1,
            ranking: 1,
            cnyAmt: 199,
            dateRadio: 1,
          },
          {
            directName: "线上",
            marketChannel: "拼多多",
            marketCenter: null,
            cooprLevel2Mmanager: "张茉欧",
            saleTaskAmt: "22",
            cnyAmt: 22,
            cnyAmtRadio: 22,
            cnyAmtRadio: 22,
            turnoverDays: 22,
            ProfitRadio: 22,
            turnoverDays: 22,
            amtFinish: 1,
            ranking: 1,
            cnyAmt: 199,
            dateRadio: 1,
          },
          {
            directName: "线上",
            marketChannel: "美的平台",
            marketCenter: null,
            cooprLevel2Mmanager: "张茉欧",
            saleTaskAmt: "22",
            cnyAmt: 22,
            cnyAmtRadio: 22,
            cnyAmtRadio: 22,
            turnoverDays: 22,
            turnoverDays: 22,
            ProfitRadio: 22,
            amtFinish: 1,
            ranking: 1,
            cnyAmt: 199,
            dateRadio: 1,
          },
          {
            directName: "线上",
            marketChannel: "兴趣电商",
            marketCenter: null,
            cooprLevel2Mmanager: "张茉欧",
            saleTaskAmt: "22",
            cnyAmt: 22,
            cnyAmtRadio: 22,
            cnyAmtRadio: 22,
            ProfitRadio: 22,
            turnoverDays: 22,
            turnoverDays: 22,
            amtFinish: 1,
            ranking: 1,
            cnyAmt: 199,
            dateRadio: 1,
          },
          {
            directName: "线上",
            marketChannel: "天猫",
            marketCenter: null,
            cooprLevel2Mmanager: "张茉欧",
            saleTaskAmt: "22",
            cnyAmt: 22,
            ProfitRadio: 22,
            cnyAmtRadio: 22,
            cnyAmtRadio: 22,
            turnoverDays: 22,
            turnoverDays: 22,
            amtFinish: 1,
            ranking: 1,
            cnyAmt: 199,
            dateRadio: 1,
          },
          {
            directName: "线上",
            marketChannel: "合计",
            marketCenter: null,
            cooprLevel2Mmanager: "张茉欧",
            saleTaskAmt: "22",
            cnyAmt: 22,
            ProfitRadio: 22,
            cnyAmtRadio: 22,
            cnyAmtRadio: 22,
            turnoverDays: 22,
            turnoverDays: 22,
            amtFinish: 1,
            ranking: 1,
            cnyAmt: 199,
            dateRadio: 1,
          },
        ],
      },
      demosticDirectOnOnlineShop: {
        title: {
          manager: "责任人",
          managerSystem: "责任制",
          businessEntityName1: "累计达成",
          businessEntityName2: "任务完成率",
          businessEntityName3: "毛利率",
          businessEntityName4: "周转天数",
          businessEntityName5: "说到做到",
          businessEntityName6: "排名",
        },
        innerDirect: [
          {
            directName: "线下",
            marketChannel: "破壁机",
            marketCenter: null,
            cooprLevel2Mmanager: "张茉欧",
            saleTaskAmt: "22",
            cnyAmt: 22,
            ProfitRadio: 22,
            cnyAmtRadio: 22,
            cnyAmtRadio: 22,
            turnoverDays: 22,
            turnoverDays: 22,
            amtFinish: 1,
            ranking: 1,
            cnyAmt: 199,
            dateRadio: 1,
          },
          {
            directName: "线下",
            marketChannel: "豆浆机",
            marketCenter: null,
            cooprLevel2Mmanager: "张茉欧",
            saleTaskAmt: "22",
            cnyAmt: 22,
            ProfitRadio: 22,
            cnyAmtRadio: 22,
            cnyAmtRadio: 22,
            turnoverDays: 22,
            turnoverDays: 22,
            amtFinish: 1,
            ranking: 1,
            cnyAmt: 199,
            dateRadio: 1,
          },
          {
            directName: "线下",
            marketChannel: "绞肉机",
            marketCenter: null,
            cooprLevel2Mmanager: "张茉欧",
            saleTaskAmt: "22",
            cnyAmt: 22,
            cnyAmtRadio: 22,
            cnyAmtRadio: 22,
            turnoverDays: 22,
            ProfitRadio: 22,
            turnoverDays: 22,
            amtFinish: 1,
            ranking: 1,
            cnyAmt: 199,
            dateRadio: 1,
          },
          {
            directName: "线下",
            marketChannel: "洗衣机",
            marketCenter: null,
            cooprLevel2Mmanager: "张茉欧",
            saleTaskAmt: "22",
            ProfitRadio: 22,
            cnyAmt: 22,
            cnyAmtRadio: 22,
            cnyAmtRadio: 22,
            turnoverDays: 22,
            turnoverDays: 22,
            amtFinish: 1,
            ranking: 1,
            cnyAmt: 199,
            dateRadio: 1,
          },
          {
            directName: "线下",
            marketChannel: "吹风机",
            marketCenter: null,
            cooprLevel2Mmanager: "张茉欧",
            saleTaskAmt: "22",
            ProfitRadio: 22,
            cnyAmt: 22,
            cnyAmtRadio: 22,
            cnyAmtRadio: 22,
            turnoverDays: 22,
            turnoverDays: 22,
            amtFinish: 1,
            ranking: 1,
            cnyAmt: 199,
            dateRadio: 1,
          },
          {
            directName: "线下",
            ProfitRadio: 22,
            marketChannel: "其他",
            marketCenter: null,
            cooprLevel2Mmanager: "张茉欧",
            saleTaskAmt: "22",
            cnyAmt: 22,
            cnyAmtRadio: 22,
            cnyAmtRadio: 22,
            turnoverDays: 22,
            turnoverDays: 22,
            amtFinish: 1,
            ranking: 1,
            cnyAmt: 199,
            dateRadio: 1,
          },
          {
            directName: "内销",
            ProfitRadio: 22,
            marketChannel: "合计",
            marketCenter: null,
            manager: "张茉欧",
            managerSystem: "199",
            businessEntityName1: 199,
            businessEntityName2: 199,
            businessEntityName3: 199,
            businessEntityName4: 199,
            businessEntityName5: 199,
            businessEntityName6: null,
            saleVolume2: 30,
            saleVolume5: 30,
            completeRadioAll: null,
            cnyAmt: 2770085.0577,
            saleTaskAmt: 18,
            dateRadio: 1,
          },
        ],
        outerDirect: [
          {
            directName: "线下",
            ProfitRadio: 22,
            marketChannel: "型号1",
            marketCenter: null,
            cooprLevel2Mmanager: "张茉欧",
            saleTaskAmt: "22",
            cnyAmt: 22,
            cnyAmtRadio: 22,
            cnyAmtRadio: 22,
            turnoverDays: 22,
            turnoverDays: 22,
            amtFinish: 1,
            ranking: 1,
            cnyAmt: 199,
            dateRadio: 1,
          },
          {
            directName: "线下",
            ProfitRadio: 22,
            marketChannel: "型号2",
            marketCenter: null,
            cooprLevel2Mmanager: "张茉欧",
            saleTaskAmt: "22",
            cnyAmt: 22,
            cnyAmtRadio: 22,
            cnyAmtRadio: 22,
            turnoverDays: 22,
            turnoverDays: 22,
            amtFinish: 1,
            ranking: 1,
            cnyAmt: 199,
            dateRadio: 1,
          },
          {
            directName: "线下",
            ProfitRadio: 22,
            marketChannel: "型号3",
            marketCenter: null,
            cooprLevel2Mmanager: "张茉欧",
            saleTaskAmt: "22",
            cnyAmt: 22,
            cnyAmtRadio: 22,
            cnyAmtRadio: 22,
            turnoverDays: 22,
            turnoverDays: 22,
            amtFinish: 1,
            ranking: 1,
            cnyAmt: 199,
            dateRadio: 1,
          },
          {
            directName: "线下",
            ProfitRadio: 22,
            marketChannel: "型号4",
            marketCenter: null,
            cooprLevel2Mmanager: "张茉欧",
            saleTaskAmt: "22",
            cnyAmt: 22,
            cnyAmtRadio: 22,
            cnyAmtRadio: 22,
            turnoverDays: 22,
            turnoverDays: 22,
            amtFinish: 1,
            ranking: 1,
            cnyAmt: 199,
            dateRadio: 1,
          },
          {
            directName: "线下",
            ProfitRadio: 22,
            marketChannel: "型号5",
            marketCenter: null,
            cooprLevel2Mmanager: "张茉欧",
            saleTaskAmt: "22",
            cnyAmt: 22,
            cnyAmtRadio: 22,
            cnyAmtRadio: 22,
            turnoverDays: 22,
            turnoverDays: 22,
            amtFinish: 1,
            ranking: 1,
            cnyAmt: 199,
            dateRadio: 1,
          },
          {
            directName: "线下",
            marketChannel: "其他",
            marketCenter: null,
            cooprLevel2Mmanager: "张茉欧",
            ProfitRadio: 22,
            saleTaskAmt: "22",
            cnyAmt: 22,
            cnyAmtRadio: 22,
            cnyAmtRadio: 22,
            turnoverDays: 22,
            turnoverDays: 22,
            amtFinish: 1,
            cnyAmt: 199,
            dateRadio: 1,
          },
          {
            directName: "线下",
            marketChannel: "合计",
            marketCenter: null,
            cooprLevel2Mmanager: "张茉欧",
            saleTaskAmt: "22",
            cnyAmt: 22,
            cnyAmtRadio: 22,
            cnyAmtRadio: 22,
            turnoverDays: 22,
            turnoverDays: 22,
            amtFinish: 1,
            ranking: 1,
            cnyAmt: 199,
            dateRadio: 1,
          },
        ],
      },
      offlineDetail: {
        title: {
          manager: "责任人",
          managerSystem: "责任制",
          businessEntityName1: "累计达成",
          businessEntityName2: "任务完成率",
          businessEntityName3: "毛利率",
          businessEntityName4: "周转天数",
          businessEntityName5: "说到做到",
          businessEntityName6: "排名",
        },
        innerDirect: [
          {
            directName: "线下",
            marketChannel: "苏宁",
            marketCenter: null,
            cooprLevel2Mmanager: "张茉欧",
            saleTaskAmt: "22",
            ProfitRadio: 22,
            cnyAmt: 22,
            cnyAmtRadio: 22,
            cnyAmtRadio: 22,
            turnoverDays: 22,
            turnoverDays: 22,
            amtFinish: 1,
            ranking: 1,
            cnyAmt: 199,
            dateRadio: 1,
          },
          {
            directName: "线下",
            marketChannel: "天猫",
            marketCenter: null,
            cooprLevel2Mmanager: "张茉欧",
            saleTaskAmt: "22",
            ProfitRadio: 22,
            cnyAmt: 22,
            cnyAmtRadio: 22,
            cnyAmtRadio: 22,
            turnoverDays: 22,
            turnoverDays: 22,
            amtFinish: 1,
            ranking: 1,
            cnyAmt: 199,
            dateRadio: 1,
          },
          {
            directName: "线下",
            marketChannel: "淘宝",
            marketCenter: null,
            cooprLevel2Mmanager: "张茉欧",
            saleTaskAmt: "22",
            cnyAmt: 22,
            ProfitRadio: 22,
            cnyAmtRadio: 22,
            cnyAmtRadio: 22,
            turnoverDays: 22,
            turnoverDays: 22,
            amtFinish: 1,
            ranking: 1,
            cnyAmt: 199,
            dateRadio: 1,
          },
          {
            directName: "线下",
            marketChannel: "拼多多",
            marketCenter: null,
            cooprLevel2Mmanager: "张茉欧",
            saleTaskAmt: "22",
            cnyAmt: 22,
            ProfitRadio: 22,
            cnyAmtRadio: 22,
            cnyAmtRadio: 22,
            turnoverDays: 22,
            turnoverDays: 22,
            amtFinish: 1,
            ranking: 1,
            cnyAmt: 199,
            dateRadio: 1,
          },
          {
            directName: "线下",
            marketChannel: "分中心",
            ProfitRadio: 22,
            marketCenter: null,
            cooprLevel2Mmanager: "张茉欧",
            saleTaskAmt: "22",
            cnyAmt: 22,
            cnyAmtRadio: 22,
            cnyAmtRadio: 22,
            turnoverDays: 22,
            turnoverDays: 22,
            amtFinish: 1,
            ranking: 1,
            cnyAmt: 199,
            dateRadio: 1,
          },
          {
            directName: "线下",
            marketChannel: "其他",
            ProfitRadio: 22,
            marketCenter: null,
            cooprLevel2Mmanager: "张茉欧",
            saleTaskAmt: "22",
            cnyAmt: 22,
            cnyAmtRadio: 22,
            cnyAmtRadio: 22,
            turnoverDays: 22,
            turnoverDays: 22,
            amtFinish: 1,
            ranking: 1,
            cnyAmt: 199,
            dateRadio: 1,
          },
          {
            directName: "线下",
            marketChannel: "合计",
            marketCenter: null,
            cooprLevel2Mmanager: "张茉欧",
            saleTaskAmt: "22",
            cnyAmt: 22,
            cnyAmtRadio: 22,
            cnyAmtRadio: 22,
            turnoverDays: 22,
            turnoverDays: 22,
            amtFinish: 1,
            cnyAmt: 199,
            dateRadio: 1,
          },
        ],
        outerDirect: [
          {
            directName: "线下",
            marketChannel: "客户1",
            marketCenter: null,
            cooprLevel2Mmanager: "张茉欧",
            saleTaskAmt: "22",
            cnyAmt: 22,
            cnyAmtRadio: 22,
            ProfitRadio: 22,
            cnyAmtRadio: 22,
            turnoverDays: 22,
            turnoverDays: 22,
            amtFinish: 1,
            ranking: 1,
            cnyAmt: 199,
            dateRadio: 1,
          },
          {
            directName: "线下",
            marketChannel: "客户2",
            marketCenter: null,
            ProfitRadio: 22,
            cooprLevel2Mmanager: "张茉欧",
            saleTaskAmt: "22",
            cnyAmt: 22,
            cnyAmtRadio: 22,
            cnyAmtRadio: 22,
            turnoverDays: 22,
            turnoverDays: 22,
            amtFinish: 1,
            ranking: 1,
            cnyAmt: 199,
            dateRadio: 1,
          },
          {
            directName: "线下",
            marketChannel: "客户3",
            ProfitRadio: 22,
            marketCenter: null,
            cooprLevel2Mmanager: "张茉欧",
            saleTaskAmt: "22",
            cnyAmt: 22,
            cnyAmtRadio: 22,
            cnyAmtRadio: 22,
            turnoverDays: 22,
            turnoverDays: 22,
            amtFinish: 1,
            ranking: 1,
            cnyAmt: 199,
            dateRadio: 1,
          },
          {
            directName: "线下",
            marketChannel: "客户4",
            ProfitRadio: 22,
            marketCenter: null,
            cooprLevel2Mmanager: "张茉欧",
            saleTaskAmt: "22",
            cnyAmt: 22,
            cnyAmtRadio: 22,
            cnyAmtRadio: 22,
            turnoverDays: 22,
            turnoverDays: 22,
            amtFinish: 1,
            ranking: 1,
            cnyAmt: 199,
            dateRadio: 1,
          },
          {
            directName: "线下",
            marketChannel: "客户5",
            ProfitRadio: 22,
            marketCenter: null,
            cooprLevel2Mmanager: "张茉欧",
            saleTaskAmt: "22",
            cnyAmt: 22,
            cnyAmtRadio: 22,
            cnyAmtRadio: 22,
            turnoverDays: 22,
            turnoverDays: 22,
            amtFinish: 1,
            ranking: 1,
            cnyAmt: 199,
            dateRadio: 1,
          },
          {
            directName: "线下",
            marketChannel: "其他",
            ProfitRadio: 22,
            marketCenter: null,
            cooprLevel2Mmanager: "张茉欧",
            saleTaskAmt: "22",
            cnyAmt: 22,
            cnyAmtRadio: 22,
            cnyAmtRadio: 22,
            turnoverDays: 22,
            turnoverDays: 22,
            amtFinish: 1,
            ranking: 1,
            cnyAmt: 199,
            dateRadio: 1,
          },
          {
            directName: "线下",
            marketChannel: "合计",
            marketCenter: null,
            cooprLevel2Mmanager: "张茉欧",
            saleTaskAmt: "22",
            cnyAmt: 22,
            cnyAmtRadio: 22,
            cnyAmtRadio: 22,
            turnoverDays: 22,
            turnoverDays: 22,
            amtFinish: 1,
            cnyAmt: 199,
            dateRadio: 1,
          },
        ],
      },
      placeArea: {
        title: {
          manager: "责任人",
          managerSystem: "责任制",
          businessEntityName1: "累计达成",
          businessEntityName2: "任务完成率",
          businessEntityName3: "毛利率",
          businessEntityName4: "周转天数",
          businessEntityName5: "说到做到",
          businessEntityName6: "排名",
        },
        innerDirect: [
          {
            directName: "线下",
            marketChannel: "中东非",
            marketCenter: null,
            ProfitRadio: 22,
            cooprLevel2Mmanager: "张茉欧",
            saleTaskAmt: "22",
            cnyAmt: 22,
            cnyAmtRadio: 22,
            cnyAmtRadio: 22,
            turnoverDays: 22,
            turnoverDays: 22,
            amtFinish: 1,
            ranking: 1,
            cnyAmt: 199,
            dateRadio: 1,
          },
          {
            directName: "线下",
            marketChannel: "日本",
            marketCenter: null,
            ProfitRadio: 22,
            cooprLevel2Mmanager: "张茉欧",
            saleTaskAmt: "22",
            cnyAmt: 22,
            cnyAmtRadio: 22,
            cnyAmtRadio: 22,
            turnoverDays: 22,
            turnoverDays: 22,
            amtFinish: 1,
            ranking: 1,
            cnyAmt: 199,
            dateRadio: 1,
          },
          {
            directName: "线下",
            marketChannel: "韩国",
            ProfitRadio: 22,
            marketCenter: null,
            cooprLevel2Mmanager: "张茉欧",
            saleTaskAmt: "22",
            cnyAmt: 22,
            cnyAmtRadio: 22,
            cnyAmtRadio: 22,
            turnoverDays: 22,
            turnoverDays: 22,
            amtFinish: 1,
            ranking: 1,
            cnyAmt: 199,
            dateRadio: 1,
          },
          {
            directName: "线下",
            marketChannel: "西北欧",
            ProfitRadio: 22,
            marketCenter: null,
            cooprLevel2Mmanager: "张茉欧",
            saleTaskAmt: "22",
            cnyAmt: 22,
            cnyAmtRadio: 22,
            cnyAmtRadio: 22,
            turnoverDays: 22,
            turnoverDays: 22,
            amtFinish: 1,
            ranking: 1,
            cnyAmt: 199,
            dateRadio: 1,
          },
          {
            directName: "线下",
            marketChannel: "北美",
            ProfitRadio: 22,
            marketCenter: null,
            cooprLevel2Mmanager: "张茉欧",
            saleTaskAmt: "22",
            cnyAmt: 22,
            cnyAmtRadio: 22,
            cnyAmtRadio: 22,
            turnoverDays: 22,
            turnoverDays: 22,
            amtFinish: 1,
            ranking: 1,
            cnyAmt: 199,
            dateRadio: 1,
          },
          {
            directName: "线下",
            marketChannel: "亚太",
            ProfitRadio: 22,
            marketCenter: null,
            cooprLevel2Mmanager: "张茉欧",
            saleTaskAmt: "22",
            cnyAmt: 22,
            cnyAmtRadio: 22,
            cnyAmtRadio: 22,
            turnoverDays: 22,
            turnoverDays: 22,
            amtFinish: 1,
            ranking: 1,
            cnyAmt: 199,
            dateRadio: 1,
          },
          {
            directName: "线下",
            marketChannel: "合计",
            ProfitRadio: 22,
            marketCenter: null,
            cooprLevel2Mmanager: "张茉欧",
            saleTaskAmt: "22",
            cnyAmt: 22,
            cnyAmtRadio: 22,
            cnyAmtRadio: 22,
            turnoverDays: 22,
            turnoverDays: 22,
            amtFinish: 1,
            cnyAmt: 199,
            dateRadio: 1,
          },
        ],
        outerDirect: [
          {
            directName: "线下",
            marketChannel: "北美",
            ProfitRadio: 22,
            marketCenter: null,
            cooprLevel2Mmanager: "张茉欧",
            saleTaskAmt: "22",
            cnyAmt: 22,
            cnyAmtRadio: 22,
            cnyAmtRadio: 22,
            turnoverDays: 22,
            turnoverDays: 22,
            amtFinish: 1,
            ranking: 1,
            cnyAmt: 199,
            dateRadio: 1,
          },
          {
            directName: "线下",
            marketChannel: "亚太",
            marketCenter: null,
            ProfitRadio: 22,
            cooprLevel2Mmanager: "张茉欧",
            saleTaskAmt: "22",
            cnyAmt: 22,
            cnyAmtRadio: 22,
            cnyAmtRadio: 22,
            turnoverDays: 22,
            turnoverDays: 22,
            amtFinish: 1,
            ranking: 1,
            cnyAmt: 199,
            dateRadio: 1,
          },
          {
            directName: "线下",
            marketChannel: "日本",
            ProfitRadio: 22,
            marketCenter: null,
            cooprLevel2Mmanager: "张茉欧",
            saleTaskAmt: "22",
            cnyAmt: 22,
            cnyAmtRadio: 22,
            cnyAmtRadio: 22,
            turnoverDays: 22,
            turnoverDays: 22,
            amtFinish: 1,
            ranking: 1,
            cnyAmt: 199,
            dateRadio: 1,
          },
          {
            directName: "线下",
            marketChannel: "韩国",
            ProfitRadio: 22,
            marketCenter: null,
            cooprLevel2Mmanager: "张茉欧",
            saleTaskAmt: "22",
            cnyAmt: 22,
            cnyAmtRadio: 22,
            cnyAmtRadio: 22,
            turnoverDays: 22,
            turnoverDays: 22,
            amtFinish: 1,
            ranking: 1,
            cnyAmt: 199,
            dateRadio: 1,
          },
          {
            directName: "线下",
            marketChannel: "亚太",
            ProfitRadio: 22,
            marketCenter: null,
            cooprLevel2Mmanager: "张茉欧",
            saleTaskAmt: "22",
            cnyAmt: 22,
            cnyAmtRadio: 22,
            cnyAmtRadio: 22,
            turnoverDays: 22,
            turnoverDays: 22,
            amtFinish: 1,
            ranking: 1,
            cnyAmt: 199,
            dateRadio: 1,
          },
          {
            directName: "线下",
            marketChannel: "西北欧",
            ProfitRadio: 22,
            marketCenter: null,
            cooprLevel2Mmanager: "张茉欧",
            saleTaskAmt: "22",
            cnyAmt: 22,
            cnyAmtRadio: 22,
            cnyAmtRadio: 22,
            turnoverDays: 22,
            turnoverDays: 22,
            amtFinish: 1,
            ranking: 1,
            cnyAmt: 199,
            dateRadio: 1,
          },
          {
            directName: "线下",
            marketChannel: "合计",
            marketCenter: null,
            cooprLevel2Mmanager: "张茉欧",
            saleTaskAmt: "22",
            cnyAmt: 22,
            ProfitRadio: 22,
            cnyAmtRadio: 22,
            cnyAmtRadio: 22,
            turnoverDays: 22,
            turnoverDays: 22,
            amtFinish: 1,
            cnyAmt: 199,
            dateRadio: 1,
          },
        ],
      },
      southAmerciaData: {
        title: {
          manager: "责任人",
          managerSystem: "责任制",
          businessEntityName1: "累计达成",
          businessEntityName2: "任务完成率",
          businessEntityName3: "毛利率",
          businessEntityName4: "周转天数",
          businessEntityName5: "说到做到",
          businessEntityName6: "排名",
        },
        innerDirect: [
          {
            directName: "线下",
            marketChannel: "巴西",
            marketCenter: null,
            ProfitRadio: 22,
            cooprLevel2Mmanager: "张茉欧",
            saleTaskAmt: "22",
            cnyAmt: 22,
            cnyAmtRadio: 22,
            cnyAmtRadio: 22,
            turnoverDays: 22,
            turnoverDays: 22,
            amtFinish: 1,
            ranking: 1,
            cnyAmt: 199,
            dateRadio: 1,
          },
          {
            directName: "线下",
            marketChannel: "阿根廷",
            marketCenter: null,
            ProfitRadio: 22,
            cooprLevel2Mmanager: "张茉欧",
            saleTaskAmt: "22",
            cnyAmt: 22,
            cnyAmtRadio: 22,
            cnyAmtRadio: 22,
            turnoverDays: 22,
            turnoverDays: 22,
            amtFinish: 1,
            ranking: 1,
            cnyAmt: 199,
            dateRadio: 1,
          },
          {
            directName: "线下",
            marketChannel: "哥伦比亚",
            ProfitRadio: 22,
            marketCenter: null,
            cooprLevel2Mmanager: "张茉欧",
            saleTaskAmt: "22",
            cnyAmt: 22,
            cnyAmtRadio: 22,
            cnyAmtRadio: 22,
            turnoverDays: 22,
            turnoverDays: 22,
            amtFinish: 1,
            ranking: 1,
            cnyAmt: 199,
            dateRadio: 1,
          },
          {
            directName: "线下",
            marketChannel: "智利",
            ProfitRadio: 22,
            marketCenter: null,
            cooprLevel2Mmanager: "张茉欧",
            saleTaskAmt: "22",
            cnyAmt: 22,
            cnyAmtRadio: 22,
            cnyAmtRadio: 22,
            turnoverDays: 22,
            turnoverDays: 22,
            amtFinish: 1,
            ranking: 1,
            cnyAmt: 199,
            dateRadio: 1,
          },
          {
            directName: "线下",
            marketChannel: "美国",
            ProfitRadio: 22,
            marketCenter: null,
            cooprLevel2Mmanager: "张茉欧",
            saleTaskAmt: "22",
            cnyAmt: 22,
            cnyAmtRadio: 22,
            cnyAmtRadio: 22,
            turnoverDays: 22,
            turnoverDays: 22,
            amtFinish: 1,
            ranking: 1,
            cnyAmt: 199,
            dateRadio: 1,
          },
          {
            directName: "线下",
            marketChannel: "墨西哥",
            ProfitRadio: 22,
            marketCenter: null,
            cooprLevel2Mmanager: "张茉欧",
            saleTaskAmt: "22",
            cnyAmt: 22,
            cnyAmtRadio: 22,
            cnyAmtRadio: 22,
            turnoverDays: 22,
            turnoverDays: 22,
            amtFinish: 1,
            ranking: 1,
            cnyAmt: 199,
            dateRadio: 1,
          },
          {
            directName: "线下",
            marketChannel: "合计",
            marketCenter: null,
            ProfitRadio: 22,
            cooprLevel2Mmanager: "张茉欧",
            saleTaskAmt: "22",
            cnyAmt: 22,
            cnyAmtRadio: 22,
            cnyAmtRadio: 22,
            turnoverDays: 22,
            turnoverDays: 22,
            amtFinish: 1,
            cnyAmt: 199,
            dateRadio: 1,
          },
        ],
        outerDirect: [
          {
            directName: "线下",
            marketChannel: "巴西",
            marketCenter: null,
            ProfitRadio: 22,
            cooprLevel2Mmanager: "张茉欧",
            saleTaskAmt: "22",
            cnyAmt: 22,
            cnyAmtRadio: 22,
            cnyAmtRadio: 22,
            turnoverDays: 22,
            turnoverDays: 22,
            amtFinish: 1,
            ranking: 1,
            cnyAmt: 199,
            dateRadio: 1,
          },
          {
            directName: "线下",
            marketChannel: "阿根廷",
            ProfitRadio: 22,
            marketCenter: null,
            cooprLevel2Mmanager: "张茉欧",
            saleTaskAmt: "22",
            cnyAmt: 22,
            cnyAmtRadio: 22,
            cnyAmtRadio: 22,
            turnoverDays: 22,
            turnoverDays: 22,
            amtFinish: 1,
            ranking: 1,
            cnyAmt: 199,
            dateRadio: 1,
          },
          {
            directName: "线下",
            marketChannel: "哥伦比亚",
            ProfitRadio: 22,
            marketCenter: null,
            cooprLevel2Mmanager: "张茉欧",
            saleTaskAmt: "22",
            cnyAmt: 22,
            cnyAmtRadio: 22,
            cnyAmtRadio: 22,
            turnoverDays: 22,
            turnoverDays: 22,
            amtFinish: 1,
            ranking: 1,
            cnyAmt: 199,
            dateRadio: 1,
          },
          {
            directName: "线下",
            marketChannel: "智利",
            ProfitRadio: 22,
            marketCenter: null,
            cooprLevel2Mmanager: "张茉欧",
            saleTaskAmt: "22",
            cnyAmt: 22,
            cnyAmtRadio: 22,
            cnyAmtRadio: 22,
            turnoverDays: 22,
            turnoverDays: 22,
            amtFinish: 1,
            ranking: 1,
            cnyAmt: 199,
            dateRadio: 1,
          },
          {
            directName: "线下",
            marketChannel: "美国",
            ProfitRadio: 22,
            marketCenter: null,
            cooprLevel2Mmanager: "张茉欧",
            saleTaskAmt: "22",
            cnyAmt: 22,
            cnyAmtRadio: 22,
            cnyAmtRadio: 22,
            turnoverDays: 22,
            turnoverDays: 22,
            amtFinish: 1,
            ranking: 1,
            cnyAmt: 199,
            dateRadio: 1,
          },
          {
            directName: "线下",
            ProfitRadio: 22,
            marketChannel: "墨西哥",
            marketCenter: null,
            cooprLevel2Mmanager: "张茉欧",
            saleTaskAmt: "22",
            cnyAmt: 22,
            cnyAmtRadio: 22,
            cnyAmtRadio: 22,
            turnoverDays: 22,
            turnoverDays: 22,
            amtFinish: 1,
            ranking: 1,
            cnyAmt: 199,
            dateRadio: 1,
          },
          {
            directName: "线下",
            marketChannel: "合计",
            marketCenter: null,
            cooprLevel2Mmanager: "张茉欧",
            saleTaskAmt: "22",
            cnyAmt: 22,
            ProfitRadio: 22,
            cnyAmtRadio: 22,
            cnyAmtRadio: 22,
            turnoverDays: 22,
            turnoverDays: 22,
            amtFinish: 1,
            cnyAmt: 199,
            dateRadio: 1,
          },
        ],
      },
      categoryData: {
        innerDirect: [
          {
            directName: "内销",
            marketChannel: "线上",
            marketCenter: null,
            manager: "张茉欧",
            cooprMode: "台扇",
            businessEntityName1: 23,
            businessEntityName2: 23,
            businessEntityName3: 23,
            businessEntityName4: 23,
            businessEntityName5: 23,
            businessEntityName6: 23,
            saleVolume1: 34,
            saleVolume2: 34,
            saleVolume3: 34,
            saleVolume4: 34,
            saleVolume5: 34,
            saleVolume6: 34,
            completeRadioAll: null,
            cnyAmt: 22,
            saleTaskAmt: 60,
            saleVolumeAll: 50,
            dateRadio: 1,
          },
          {
            directName: "内销",
            marketChannel: "线上",
            marketCenter: null,
            manager: "张茉欧",
            cooprMode: "循环扇",
            businessEntityName1: 23,
            businessEntityName2: 23,
            businessEntityName3: 23,
            businessEntityName4: 23,
            businessEntityName5: 23,
            businessEntityName6: 23,
            saleVolume1: 34,
            saleVolume2: 34,
            saleVolume3: 34,
            saleVolume4: 34,
            saleVolume5: 34,
            saleVolume6: 34,
            completeRadioAll: null,
            cnyAmt: 23,
            saleTaskAmt: 60,
            saleVolumeAll: 50,
            dateRadio: 1,
          },
          {
            directName: "内销",
            marketChannel: "线上",
            marketCenter: null,
            manager: "张茉欧",
            cooprMode: "无叶风扇",
            businessEntityName1: 23,
            businessEntityName2: 23,
            businessEntityName3: 23,
            businessEntityName4: 23,
            businessEntityName5: 23,
            businessEntityName6: 23,
            saleVolume1: 34,
            saleVolume2: 34,
            saleVolume3: 34,
            saleVolume4: 34,
            saleVolume5: 34,
            saleVolume6: 34,
            completeRadioAll: null,
            cnyAmt: 24,
            saleTaskAmt: 60,
            saleVolumeAll: 50,
            dateRadio: 1,
          },
          {
            directName: "内销",
            marketChannel: "线下",
            marketCenter: null,
            manager: "张茉欧",
            cooprMode: "空净品类",
            businessEntityName1: 23,
            businessEntityName2: 23,
            businessEntityName3: 23,
            businessEntityName4: 23,
            businessEntityName5: 23,
            businessEntityName6: 23,
            saleVolume1: 34,
            saleVolume2: 34,
            saleVolume3: 34,
            saleVolume4: 34,
            saleVolume5: 34,
            saleVolume6: 34,
            completeRadioAll: null,
            cnyAmt: 24,
            saleTaskAmt: 60,
            saleVolumeAll: 50,
            dateRadio: 1,
          },
          {
            directName: "内销",
            marketChannel: "线下",
            marketCenter: null,
            manager: "张茉欧",
            cooprMode: "挂烫机",
            businessEntityName1: 23,
            businessEntityName2: 23,
            businessEntityName3: 23,
            businessEntityName4: 23,
            businessEntityName5: 23,
            businessEntityName6: 23,
            saleVolume1: 34,
            saleVolume2: 34,
            saleVolume3: 34,
            saleVolume4: 34,
            saleVolume5: 34,
            saleVolume6: 34,
            completeRadioAll: null,
            cnyAmt: 24,
            saleTaskAmt: 60,
            saleVolumeAll: 50,
            dateRadio: 1,
          },
          {
            directName: "内销",
            marketChannel: "线下",
            marketCenter: null,
            manager: "张茉欧",
            cooprMode: "塔扇",
            businessEntityName1: 23,
            businessEntityName2: 23,
            businessEntityName3: 23,
            businessEntityName4: 23,
            businessEntityName5: 23,
            businessEntityName6: 23,
            saleVolume1: 34,
            saleVolume2: 34,
            saleVolume3: 34,
            saleVolume4: 34,
            saleVolume5: 34,
            saleVolume6: 34,
            completeRadioAll: null,
            cnyAmt: 24,
            saleTaskAmt: 60,
            saleVolumeAll: 50,
            dateRadio: 1,
          },
          {
            directName: "外销",
            marketChannel: "合计",
            cooprMode: "",
            marketCenter: null,
            manager: null,
            businessEntityName1: 23,
            businessEntityName2: 23,
            businessEntityName3: 23,
            businessEntityName4: 23,
            businessEntityName5: 23,
            businessEntityName6: 23,
            saleVolume1: 34,
            saleVolume2: 34,
            saleVolume3: 34,
            saleVolume4: 34,
            saleVolume5: 34,
            saleVolume6: 34,
            completeRadioAll: null,
            cnyAmt: 24,
            saleTaskAmt: 60,
            saleVolumeAll: 50,
            dateRadio: 1,
          },
        ],
        outerDirect: [
          {
            directName: "外销",
            marketChannel: "大区",
            marketCenter: null,
            manager: null,
            cooprMode: "台扇",
            businessEntityName1: 23,
            businessEntityName2: 23,
            businessEntityName3: 23,
            businessEntityName4: 23,
            businessEntityName5: 23,
            businessEntityName6: 23,
            saleVolume1: 34,
            saleVolume2: 34,
            saleVolume3: 34,
            saleVolume4: 34,
            saleVolume5: 34,
            saleVolume6: 34,
            completeRadioAll: null,
            cnyAmt: 24,
            saleTaskAmt: 60,
            saleVolumeAll: 50,
            dateRadio: 1,
          },
          {
            directName: "外销",
            marketChannel: "大区",
            cooprMode: "循环扇",
            marketCenter: null,
            manager: null,
            businessEntityName1: 23,
            businessEntityName2: 23,
            businessEntityName3: 23,
            businessEntityName4: 23,
            businessEntityName5: 23,
            businessEntityName6: 23,
            saleVolume1: 34,
            saleVolume2: 34,
            saleVolume3: 34,
            saleVolume4: 34,
            saleVolume5: 34,
            saleVolume6: 34,
            completeRadioAll: null,
            cnyAmt: 24,
            saleTaskAmt: 60,
            saleVolumeAll: 50,
            dateRadio: 1,
          },
          {
            directName: "外销",
            marketChannel: "大区",
            cooprMode: "无叶风扇",
            marketCenter: null,
            manager: null,
            businessEntityName1: 23,
            businessEntityName2: 23,
            businessEntityName3: 23,
            businessEntityName4: 23,
            businessEntityName5: 23,
            businessEntityName6: 23,
            saleVolume1: 34,
            saleVolume2: 34,
            saleVolume3: 34,
            saleVolume4: 34,
            saleVolume5: 34,
            saleVolume6: 34,
            completeRadioAll: null,
            cnyAmt: 24,
            saleTaskAmt: 60,
            saleVolumeAll: 50,
            dateRadio: 1,
          },
          {
            directName: "外销",
            marketChannel: "大区",
            cooprMode: "空净品类",
            marketCenter: null,
            manager: null,
            businessEntityName1: 23,
            businessEntityName2: 23,
            businessEntityName3: 23,
            businessEntityName4: 23,
            businessEntityName5: 23,
            businessEntityName6: 23,
            saleVolume1: 34,
            saleVolume2: 34,
            saleVolume3: 34,
            saleVolume4: 34,
            saleVolume5: 34,
            saleVolume6: 34,
            completeRadioAll: null,
            cnyAmt: 24,
            saleTaskAmt: 60,
            saleVolumeAll: 50,
            dateRadio: 1,
          },
          {
            directName: "外销",
            marketChannel: "大区",
            cooprMode: "挂烫机",
            marketCenter: null,
            manager: null,
            businessEntityName1: 23,
            businessEntityName2: 23,
            businessEntityName3: 23,
            businessEntityName4: 23,
            businessEntityName5: 23,
            businessEntityName6: 23,
            saleVolume1: 34,
            saleVolume2: 34,
            saleVolume3: 34,
            saleVolume4: 34,
            saleVolume5: 34,
            saleVolume6: 34,
            completeRadioAll: null,
            cnyAmt: 24,
            saleTaskAmt: 60,
            saleVolumeAll: 50,
            dateRadio: 1,
          },
          {
            directName: "外销",
            marketChannel: "大区",
            cooprMode: "塔扇",
            marketCenter: null,
            manager: null,
            businessEntityName1: 23,
            businessEntityName2: 23,
            businessEntityName3: 23,
            businessEntityName4: 23,
            businessEntityName5: 23,
            businessEntityName6: 23,
            saleVolume1: 34,
            saleVolume2: 34,
            saleVolume3: 34,
            saleVolume4: 34,
            saleVolume5: 34,
            saleVolume6: 34,
            completeRadioAll: null,
            cnyAmt: 24,
            saleTaskAmt: 60,
            saleVolumeAll: 50,
            dateRadio: 1,
          },
          {
            directName: "外销",
            marketChannel: "合计",
            cooprMode: "拉美",
            marketCenter: null,
            manager: null,
            businessEntityName1: 23,
            businessEntityName2: 23,
            businessEntityName3: 23,
            businessEntityName4: 23,
            businessEntityName5: 23,
            businessEntityName6: 23,
            saleVolume1: 34,
            saleVolume2: 34,
            saleVolume3: 34,
            saleVolume4: 34,
            saleVolume5: 34,
            saleVolume6: 34,
            completeRadioAll: null,
            cnyAmt: 24,
            saleTaskAmt: 60,
            saleVolumeAll: 50,
            dateRadio: 1,
          },
        ],
        title: {
          businessEntityName1: "环境",
          businessEntityName2: "烹饪",
          businessEntityName3: "电磁",
          businessEntityName4: "调理",
          businessEntityName5: "电动",
          businessEntityName6: "饮品",
        },
      },
      outlineComp: {
        innerDirect: [
          {
            directName: "内销",
            marketChannel: "北美KA",
            marketCenter: null,
            manager: "张茉欧",
            cooprMode: "台扇",
            businessEntityName1: 23,
            businessEntityName2: 23,
            businessEntityName3: 23,
            businessEntityName4: 23,
            businessEntityName5: 23,
            businessEntityName6: 23,
            saleVolume1: 34,
            saleVolume2: 34,
            saleVolume3: 34,
            saleVolume4: 34,
            saleVolume5: 34,
            saleVolume6: 34,
            completeRadioAll: null,
            cnyAmt: 22,
            saleTaskAmt: 60,
            saleVolumeAll: 50,
            dateRadio: 1,
          },
          {
            directName: "内销",
            marketChannel: "亚太",
            marketCenter: null,
            manager: "张茉欧",
            cooprMode: "循环扇",
            businessEntityName1: 23,
            businessEntityName2: 23,
            businessEntityName3: 23,
            businessEntityName4: 23,
            businessEntityName5: 23,
            businessEntityName6: 23,
            saleVolume1: 34,
            saleVolume2: 34,
            saleVolume3: 34,
            saleVolume4: 34,
            saleVolume5: 34,
            saleVolume6: 34,
            completeRadioAll: null,
            cnyAmt: 23,
            saleTaskAmt: 60,
            saleVolumeAll: 50,
            dateRadio: 1,
          },
          {
            directName: "内销",
            marketChannel: "中东非",
            marketCenter: null,
            manager: "张茉欧",
            cooprMode: "无叶风扇",
            businessEntityName1: 23,
            businessEntityName2: 23,
            businessEntityName3: 23,
            businessEntityName4: 23,
            businessEntityName5: 23,
            businessEntityName6: 23,
            saleVolume1: 34,
            saleVolume2: 34,
            saleVolume3: 34,
            saleVolume4: 34,
            saleVolume5: 34,
            saleVolume6: 34,
            completeRadioAll: null,
            cnyAmt: 24,
            saleTaskAmt: 60,
            saleVolumeAll: 50,
            dateRadio: 1,
          },
          {
            directName: "内销",
            marketChannel: "日本",
            marketCenter: null,
            manager: "张茉欧",
            cooprMode: "空净品类",
            businessEntityName1: 23,
            businessEntityName2: 23,
            businessEntityName3: 23,
            businessEntityName4: 23,
            businessEntityName5: 23,
            businessEntityName6: 23,
            saleVolume1: 34,
            saleVolume2: 34,
            saleVolume3: 34,
            saleVolume4: 34,
            saleVolume5: 34,
            saleVolume6: 34,
            completeRadioAll: null,
            cnyAmt: 24,
            saleTaskAmt: 60,
            saleVolumeAll: 50,
            dateRadio: 1,
          },
          {
            directName: "内销",
            marketChannel: "韩国",
            marketCenter: null,
            manager: "张茉欧",
            cooprMode: "挂烫机",
            businessEntityName1: 23,
            businessEntityName2: 23,
            businessEntityName3: 23,
            businessEntityName4: 23,
            businessEntityName5: 23,
            businessEntityName6: 23,
            saleVolume1: 34,
            saleVolume2: 34,
            saleVolume3: 34,
            saleVolume4: 34,
            saleVolume5: 34,
            saleVolume6: 34,
            completeRadioAll: null,
            cnyAmt: 24,
            saleTaskAmt: 60,
            saleVolumeAll: 50,
            dateRadio: 1,
          },
          {
            directName: "内销",
            marketChannel: "西北欧",
            marketCenter: null,
            manager: "张茉欧",
            cooprMode: "塔扇",
            businessEntityName1: 23,
            businessEntityName2: 23,
            businessEntityName3: 23,
            businessEntityName4: 23,
            businessEntityName5: 23,
            businessEntityName6: 23,
            saleVolume1: 34,
            saleVolume2: 34,
            saleVolume3: 34,
            saleVolume4: 34,
            saleVolume5: 34,
            saleVolume6: 34,
            completeRadioAll: null,
            cnyAmt: 24,
            saleTaskAmt: 60,
            saleVolumeAll: 50,
            dateRadio: 1,
          },
          {
            directName: "外销",
            marketChannel: "合计",
            cooprMode: "",
            marketCenter: null,
            manager: null,
            businessEntityName1: 23,
            businessEntityName2: 23,
            businessEntityName3: 23,
            businessEntityName4: 23,
            businessEntityName5: 23,
            businessEntityName6: 23,
            saleVolume1: 34,
            saleVolume2: 34,
            saleVolume3: 34,
            saleVolume4: 34,
            saleVolume5: 34,
            saleVolume6: 34,
            completeRadioAll: null,
            cnyAmt: 24,
            saleTaskAmt: 60,
            saleVolumeAll: 50,
            dateRadio: 1,
          },
        ],
        outerDirect: [
          {
            directName: "外销",
            marketChannel: "北美KA",
            marketCenter: null,
            manager: null,
            cooprMode: "台扇",
            businessEntityName1: 23,
            businessEntityName2: 23,
            businessEntityName3: 23,
            businessEntityName4: 23,
            businessEntityName5: 23,
            businessEntityName6: 23,
            saleVolume1: 34,
            saleVolume2: 34,
            saleVolume3: 34,
            saleVolume4: 34,
            saleVolume5: 34,
            saleVolume6: 34,
            completeRadioAll: null,
            cnyAmt: 24,
            saleTaskAmt: 60,
            saleVolumeAll: 50,
            dateRadio: 1,
          },
          {
            directName: "外销",
            marketChannel: "亚太",
            cooprMode: "循环扇",
            marketCenter: null,
            manager: null,
            businessEntityName1: 23,
            businessEntityName2: 23,
            businessEntityName3: 23,
            businessEntityName4: 23,
            businessEntityName5: 23,
            businessEntityName6: 23,
            saleVolume1: 34,
            saleVolume2: 34,
            saleVolume3: 34,
            saleVolume4: 34,
            saleVolume5: 34,
            saleVolume6: 34,
            completeRadioAll: null,
            cnyAmt: 24,
            saleTaskAmt: 60,
            saleVolumeAll: 50,
            dateRadio: 1,
          },
          {
            directName: "外销",
            marketChannel: "中东非",
            cooprMode: "无叶风扇",
            marketCenter: null,
            manager: null,
            businessEntityName1: 23,
            businessEntityName2: 23,
            businessEntityName3: 23,
            businessEntityName4: 23,
            businessEntityName5: 23,
            businessEntityName6: 23,
            saleVolume1: 34,
            saleVolume2: 34,
            saleVolume3: 34,
            saleVolume4: 34,
            saleVolume5: 34,
            saleVolume6: 34,
            completeRadioAll: null,
            cnyAmt: 24,
            saleTaskAmt: 60,
            saleVolumeAll: 50,
            dateRadio: 1,
          },
          {
            directName: "外销",
            marketChannel: "日本",
            cooprMode: "空净品类",
            marketCenter: null,
            manager: null,
            businessEntityName1: 23,
            businessEntityName2: 23,
            businessEntityName3: 23,
            businessEntityName4: 23,
            businessEntityName5: 23,
            businessEntityName6: 23,
            saleVolume1: 34,
            saleVolume2: 34,
            saleVolume3: 34,
            saleVolume4: 34,
            saleVolume5: 34,
            saleVolume6: 34,
            completeRadioAll: null,
            cnyAmt: 24,
            saleTaskAmt: 60,
            saleVolumeAll: 50,
            dateRadio: 1,
          },
          {
            directName: "外销",
            marketChannel: "韩国",
            cooprMode: "挂烫机",
            marketCenter: null,
            manager: null,
            businessEntityName1: 23,
            businessEntityName2: 23,
            businessEntityName3: 23,
            businessEntityName4: 23,
            businessEntityName5: 23,
            businessEntityName6: 23,
            saleVolume1: 34,
            saleVolume2: 34,
            saleVolume3: 34,
            saleVolume4: 34,
            saleVolume5: 34,
            saleVolume6: 34,
            completeRadioAll: null,
            cnyAmt: 24,
            saleTaskAmt: 60,
            saleVolumeAll: 50,
            dateRadio: 1,
          },
          {
            directName: "外销",
            marketChannel: "西北欧",
            cooprMode: "塔扇",
            marketCenter: null,
            manager: null,
            businessEntityName1: 23,
            businessEntityName2: 23,
            businessEntityName3: 23,
            businessEntityName4: 23,
            businessEntityName5: 23,
            businessEntityName6: 23,
            saleVolume1: 34,
            saleVolume2: 34,
            saleVolume3: 34,
            saleVolume4: 34,
            saleVolume5: 34,
            saleVolume6: 34,
            completeRadioAll: null,
            cnyAmt: 24,
            saleTaskAmt: 60,
            saleVolumeAll: 50,
            dateRadio: 1,
          },
          {
            directName: "外销",
            marketChannel: "合计",
            cooprMode: "拉美",
            marketCenter: null,
            manager: null,
            businessEntityName1: 23,
            businessEntityName2: 23,
            businessEntityName3: 23,
            businessEntityName4: 23,
            businessEntityName5: 23,
            businessEntityName6: 23,
            saleVolume1: 34,
            saleVolume2: 34,
            saleVolume3: 34,
            saleVolume4: 34,
            saleVolume5: 34,
            saleVolume6: 34,
            completeRadioAll: null,
            cnyAmt: 24,
            saleTaskAmt: 60,
            saleVolumeAll: 50,
            dateRadio: 1,
          },
        ],
        title: {
          businessEntityName1: "环境",
          businessEntityName2: "烹饪",
          businessEntityName3: "电磁",
          businessEntityName4: "调理",
          businessEntityName5: "电动",
          businessEntityName6: "饮品",
        },
      },
    };


  },

  methods:{
    namesClick(obj){
      // console.log('handleClick',val);
      switch(obj.marketChannel){
        case '线上':
        this.$router.push({
        name: "catSeries",
        query: { key: obj.manager },
      });
        break;
        case '线下':
        this.$router.push({
          name: "offlineCatSeries",
        query: { key: obj.manager},
      });
        break;
      }
    },
    managerClick(obj){

      this.$router.push({
        name: "exprotAreaAll",
        query: { key: obj.manager },
      });
      exprotAreaAll
    }
  }
};
</script>
<style scoped>
.table {
  width: 98%;
  height: 330px;
  display: flex;
  justify-content: space-between;
  margin: 0 auto;
}
</style>
